services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: review_agent
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
